# Generated by Django 5.2.4 on 2025-07-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_adminbored_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbored',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
